In [1]:
import os, sys
import yaml
sys.path.append("..")

In [2]:
from _8a_scraper.aggregated_ascents import get_route_ascents, get_crag_ascents
from _8a_scraper.utils import login,  get_links_to_routes_from_a_crag, get_route_ascents_from_link,\
get_sector_name_from_route_link, get_route_name_from_route_link

In [3]:
#fetch config
with open('../config/CONFIG.yaml') as stream:
    config = yaml.safe_load(stream)
#update environ
for item in config:
    os.environ[item]=config[item]

# Aggregated ascents

In [4]:
# route ascents

In [ ]:
driver = login()
route_ascents = get_route_ascents(driver, 'sportclimbing', 'Poland', 'Dolina Szklarki', 'sloneczne-skaly-df811', 'panel-sloneczny')
driver.close()

In [11]:
route_ascents.head()

,ascentId,userAvatar,userName,userSlug,date,difficulty,isHard,isSoft,type,comment,...,isSloper,isTechnical,isDanger,chipped,withKneepad,badAnchor,badBolts,highFirstBolt,looseRock,badClippingPosition
0,0,None,Natalia Szkarłat,natalia-szkarlat,2022-08-26T12:00:00+00:00,7a,False,False,rp,,...,False,True,False,False,False,False,False,False,False,False
1,0,None,Aleksandra Matys,aleksandra-matys,2022-08-25T12:00:00+00:00,7a,False,False,rp,,...,False,False,False,False,False,False,False,False,False,False
2,0,p/gallery/jd0wpkz4.jpg,Bartosz Filipów,bartosz-filipow,2022-08-25T12:00:00+00:00,7a,False,False,rp,,...,False,False,False,False,False,False,False,False,False,False
3,0,p/gallery/wggbdqi0.webp,Mikołaj Wójcik,mikolaj-wojcik,2022-08-24T12:00:00+00:00,7a,False,True,rp,,...,False,False,False,False,False,False,False,False,False,False
4,0,p/gallery/yzo0xkgz.webp,Ewa Karpęcka-Gałka,ewa-karpecka-galka,2022-08-23T12:00:00+00:00,7a,False,False,rp,,...,False,False,False,False,False,False,False,False,False,False

In [7]:
# crag ascents

In [8]:
driver = login()
crag_ascents = get_crag_ascents(driver, 'sportclimbing', 'Poland', 'Dolina Szklarki', 400, '2021-09-09T12:00:00+00:00')
driver.close()

In [9]:
crag_ascents.head()

                        date       route_name      sector_name
0  2022-08-26T12:00:00+00:00  Panel Słoneczny  Sloneczne Skaly
1  2022-08-25T12:00:00+00:00  Panel Słoneczny  Sloneczne Skaly
2  2022-08-25T12:00:00+00:00  Panel Słoneczny  Sloneczne Skaly
3  2022-08-24T12:00:00+00:00  Panel Słoneczny  Sloneczne Skaly
4  2022-08-23T12:00:00+00:00  Panel Słoneczny  Sloneczne Skaly